theme: dark
jwt_secret: [insert your token here]
default_redirection_url: https://${HOSTNAME}/terminal

server:
  host: 0.0.0.0
  port: 9091
 # path: authelia  # Add this line

log:
  level: info

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    - domain: [insert your domain here]
      policy: one_factor

session:
  name: authelia_session
  secret: [insert token here]
  expiration: 1h
  inactivity: 5m
  domain: ${HOSTNAME}

regulation:
  max_retries: 5
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: [insert generated key here]
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
