# Authelia Configuration Template
# Generate secrets with: openssl rand -hex 32

theme: dark
default_redirection_url: https://${HOSTNAME}/terminal/

server:
  address: tcp://0.0.0.0:9091

log:
  level: info

identity_validation:
  reset_password:
    jwt_secret: GENERATE_64_CHAR_SECRET_HERE

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    - domain: ${HOSTNAME}
      policy: one_factor

session:
  secret: GENERATE_64_CHAR_SECRET_HERE
  cookies:
    - domain: ${HOSTNAME}
      authelia_url: https://${HOSTNAME}/
      expiration: 1h
      inactivity: 5m

regulation:
  max_retries: 5
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: GENERATE_64_CHAR_SECRET_HERE
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
